package com.hr.mygreendao3.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.hr.mygreendao3.Dog;
import com.hr.mygreendao3.Pig;
import com.hr.mygreendao3.User;
import com.hr.mygreendao3.dao.Peo;

import com.hr.mygreendao3.dao.DogDao;
import com.hr.mygreendao3.dao.PigDao;
import com.hr.mygreendao3.dao.UserDao;
import com.hr.mygreendao3.dao.PeoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig dogDaoConfig;
    private final DaoConfig pigDaoConfig;
    private final DaoConfig userDaoConfig;
    private final DaoConfig peoDaoConfig;

    private final DogDao dogDao;
    private final PigDao pigDao;
    private final UserDao userDao;
    private final PeoDao peoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        dogDaoConfig = daoConfigMap.get(DogDao.class).clone();
        dogDaoConfig.initIdentityScope(type);

        pigDaoConfig = daoConfigMap.get(PigDao.class).clone();
        pigDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        peoDaoConfig = daoConfigMap.get(PeoDao.class).clone();
        peoDaoConfig.initIdentityScope(type);

        dogDao = new DogDao(dogDaoConfig, this);
        pigDao = new PigDao(pigDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);
        peoDao = new PeoDao(peoDaoConfig, this);

        registerDao(Dog.class, dogDao);
        registerDao(Pig.class, pigDao);
        registerDao(User.class, userDao);
        registerDao(Peo.class, peoDao);
    }
    
    public void clear() {
        dogDaoConfig.clearIdentityScope();
        pigDaoConfig.clearIdentityScope();
        userDaoConfig.clearIdentityScope();
        peoDaoConfig.clearIdentityScope();
    }

    public DogDao getDogDao() {
        return dogDao;
    }

    public PigDao getPigDao() {
        return pigDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

    public PeoDao getPeoDao() {
        return peoDao;
    }

}
